/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.api;

import mx.wire4.ApiException;
import mx.wire4.model.DepositAuthorizationRequest;
import mx.wire4.model.DepositsAuthorizationResponse;
import mx.wire4.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutorizacinDeDepsitosApi
 */
@Ignore
public class AutorizacinDeDepsitosApiTest {

    private final AutorizacinDeDepsitosApi api = new AutorizacinDeDepsitosApi();

    /**
     * Consulta autorización de depósitos
     *
     * Obtiene la información de la autorización de depósitos del contrato relacionado a la subscripción.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDepositAuthConfigurationsTest() throws ApiException {
        String authorization = null;
        String subscription = null;
        DepositsAuthorizationResponse response = api.getDepositAuthConfigurations(authorization, subscription);

        // TODO: test validations
    }
    /**
     * Des/Habilitar autorización de depósitos
     *
     * Des/Habilitar autorización de depósitos, devuelve la información final de la autorización de depósitos del contrato relacionado a la subscripción al terminar.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putDepositAuthConfigurationsTest() throws ApiException {
        DepositAuthorizationRequest body = null;
        String authorization = null;
        String subscription = null;
        DepositsAuthorizationResponse response = api.putDepositAuthConfigurations(body, authorization, subscription);

        // TODO: test validations
    }
}
