/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.api;

import mx.wire4.ApiException;
import mx.wire4.model.ErrorResponse;
import mx.wire4.model.InstitutionsList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstitucionesApi
 */
@Ignore
public class InstitucionesApiTest {

    private final InstitucionesApi api = new InstitucionesApi();

    /**
     * Consulta de instituciones bancarias
     *
     * Se obtiene un listado de las instituciones bancarias y la información de cada una de estas.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllInstitutionsUsingGETTest() throws ApiException {
        String authorization = null;
        InstitutionsList response = api.getAllInstitutionsUsingGET(authorization);

        // TODO: test validations
    }
}
