/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.api;

import mx.wire4.ApiException;
import mx.wire4.model.CodiOperationsFiltersRequestDTO;
import mx.wire4.model.ErrorResponse;
import mx.wire4.model.PagerResponseDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OperacionesCoDiApi
 */
@Ignore
public class OperacionesCoDiApiTest {

    private final OperacionesCoDiApi api = new OperacionesCoDiApi();

    /**
     * Consulta de operaciones
     *
     * Obtiene las operaciones generadas a partir de peticiones de pago CODI® de forma paginada, pudiendo aplicar filtros.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultCodiOperationsTest() throws ApiException {
        String authorization = null;
        CodiOperationsFiltersRequestDTO body = null;
        String companyId = null;
        String page = null;
        String salesPointId = null;
        String size = null;
        PagerResponseDto response = api.consultCodiOperations(authorization, body, companyId, page, salesPointId, size);

        // TODO: test validations
    }
}
