/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.api;

import mx.wire4.ApiException;
import mx.wire4.model.CodiCodeQrResponseDTO;
import mx.wire4.model.CodiCodeRequestDTO;
import mx.wire4.model.ErrorResponse;
import mx.wire4.model.PaymentRequestCodiResponseDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PeticionesDePagoPorCoDiApi
 */
@Ignore
public class PeticionesDePagoPorCoDiApiTest {

    private final PeticionesDePagoPorCoDiApi api = new PeticionesDePagoPorCoDiApi();

    /**
     * Obtiene la información de una petición de pago CODI® por orderId para un punto de venta
     *
     * Obtiene la información de una petición de pago CODI® por orderId para un punto de venta
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultCodiRequestByOrderIdTest() throws ApiException {
        String authorization = null;
        String orderId = null;
        String salesPointId = null;
        PaymentRequestCodiResponseDTO response = api.consultCodiRequestByOrderId(authorization, orderId, salesPointId);

        // TODO: test validations
    }
    /**
     * Genera un código QR para un pago mediante CODI®
     *
     * Genera un código QR solicitado por un punto de venta para un pago mediante CODI®
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void generateCodiCodeQRTest() throws ApiException {
        CodiCodeRequestDTO body = null;
        String authorization = null;
        String salesPointId = null;
        CodiCodeQrResponseDTO response = api.generateCodiCodeQR(body, authorization, salesPointId);

        // TODO: test validations
    }
}
