/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.api;

import mx.wire4.model.ErrorResponse;
import mx.wire4.model.PaymentRequestReportDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ReporteDeSolicitudesDePagosApi
 */
@Ignore
public class ReporteDeSolicitudesDePagosApiTest {

    private final ReporteDeSolicitudesDePagosApi api = new ReporteDeSolicitudesDePagosApi();

    /**
     * Consulta de solicitudes de pago por numero de orden.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void paymentRequestIdReportByOrderIdUsingGETTest() throws Exception {
        String authorization = null;
        String orderId = null;
        PaymentRequestReportDTO response = api.paymentRequestIdReportByOrderIdUsingGET(authorization, orderId);

        // TODO: test validations
    }
    /**
     * Consulta de solicitudes de pago por identificador de petición
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void paymentRequestIdReportUsingGETTest() throws Exception {
        String authorization = null;
        String requestId = null;
        PaymentRequestReportDTO response = api.paymentRequestIdReportUsingGET(authorization, requestId);

        // TODO: test validations
    }
}
