/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.api;

import mx.wire4.model.ErrorResponse;
import mx.wire4.model.PaymentRequestReq;
import mx.wire4.model.PaymentRequestResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SolicitudDePagosApi
 */
@Ignore
public class SolicitudDePagosApiTest {

    private final SolicitudDePagosApi api = new SolicitudDePagosApi();

    /**
     * Registro de solicitud de pagos
     *
     *  Se registra una solicitud de pagos. En la respuesta se proporcionará una dirección URL que lo llevará al sitio donde se le solicitará ingresar los datos de tarjeta a la que se aplicarán los cargos.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void registerPaymentRequestUsingPOSTTest() throws Exception {
        PaymentRequestReq body = null;
        String authorization = null;
        PaymentRequestResponse response = api.registerPaymentRequestUsingPOST(body, authorization);

        // TODO: test validations
    }
}
