/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import mx.wire4.model.AddressCompany;
/**
 * La información de la compañía que corresponde al contrato.
 */
@Schema(description = "La información de la compañía que corresponde al contrato.")

public class AccountDetail {
  @SerializedName("address")
  private AddressCompany address = null;

  @SerializedName("business_name")
  private String businessName = null;

  @SerializedName("constitution_date")
  private String constitutionDate = null;

  @SerializedName("emails")
  private List<String> emails = null;

  @SerializedName("legal_representatives")
  private List<String> legalRepresentatives = null;

  @SerializedName("rfc")
  private String rfc = null;

  public AccountDetail address(AddressCompany address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public AddressCompany getAddress() {
    return address;
  }

  public void setAddress(AddressCompany address) {
    this.address = address;
  }

  public AccountDetail businessName(String businessName) {
    this.businessName = businessName;
    return this;
  }

   /**
   * El nombre del negocio
   * @return businessName
  **/
  @Schema(description = "El nombre del negocio")
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  public AccountDetail constitutionDate(String constitutionDate) {
    this.constitutionDate = constitutionDate;
    return this;
  }

   /**
   * La fecha de constitución del negocio
   * @return constitutionDate
  **/
  @Schema(description = "La fecha de constitución del negocio")
  public String getConstitutionDate() {
    return constitutionDate;
  }

  public void setConstitutionDate(String constitutionDate) {
    this.constitutionDate = constitutionDate;
  }

  public AccountDetail emails(List<String> emails) {
    this.emails = emails;
    return this;
  }

  public AccountDetail addEmailsItem(String emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * La lista de correos del negocio
   * @return emails
  **/
  @Schema(description = "La lista de correos del negocio")
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(List<String> emails) {
    this.emails = emails;
  }

  public AccountDetail legalRepresentatives(List<String> legalRepresentatives) {
    this.legalRepresentatives = legalRepresentatives;
    return this;
  }

  public AccountDetail addLegalRepresentativesItem(String legalRepresentativesItem) {
    if (this.legalRepresentatives == null) {
      this.legalRepresentatives = new ArrayList<>();
    }
    this.legalRepresentatives.add(legalRepresentativesItem);
    return this;
  }

   /**
   * La lista de los representantes legales negocio
   * @return legalRepresentatives
  **/
  @Schema(description = "La lista de los representantes legales negocio")
  public List<String> getLegalRepresentatives() {
    return legalRepresentatives;
  }

  public void setLegalRepresentatives(List<String> legalRepresentatives) {
    this.legalRepresentatives = legalRepresentatives;
  }

  public AccountDetail rfc(String rfc) {
    this.rfc = rfc;
    return this;
  }

   /**
   * El RFC del negocio
   * @return rfc
  **/
  @Schema(description = "El RFC del negocio")
  public String getRfc() {
    return rfc;
  }

  public void setRfc(String rfc) {
    this.rfc = rfc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountDetail accountDetail = (AccountDetail) o;
    return Objects.equals(this.address, accountDetail.address) &&
        Objects.equals(this.businessName, accountDetail.businessName) &&
        Objects.equals(this.constitutionDate, accountDetail.constitutionDate) &&
        Objects.equals(this.emails, accountDetail.emails) &&
        Objects.equals(this.legalRepresentatives, accountDetail.legalRepresentatives) &&
        Objects.equals(this.rfc, accountDetail.rfc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, businessName, constitutionDate, emails, legalRepresentatives, rfc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountDetail {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    constitutionDate: ").append(toIndentedString(constitutionDate)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    legalRepresentatives: ").append(toIndentedString(legalRepresentatives)).append("\n");
    sb.append("    rfc: ").append(toIndentedString(rfc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
