/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import mx.wire4.model.Item;
/**
 * Es la lista de configuraciones asociadas al contrato
 */
@Schema(description = "Es la lista de configuraciones asociadas al contrato")

public class ConfigurationsLimits {
  @SerializedName("group")
  private String group = null;

  @SerializedName("items")
  private List<Item> items = null;

  public ConfigurationsLimits group(String group) {
    this.group = group;
    return this;
  }

   /**
   * Nombre del grupo de configuraciones. Debe ser LIMIT_BY_TIME para especificar la configuración por límite por horario, LIMIT_BY_RANGE para especificar límite por periodo o LIMIT_BY_SCHEDULE para especificar el horario de operaciones
   * @return group
  **/
  @Schema(description = "Nombre del grupo de configuraciones. Debe ser LIMIT_BY_TIME para especificar la configuración por límite por horario, LIMIT_BY_RANGE para especificar límite por periodo o LIMIT_BY_SCHEDULE para especificar el horario de operaciones")
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public ConfigurationsLimits items(List<Item> items) {
    this.items = items;
    return this;
  }

  public ConfigurationsLimits addItemsItem(Item itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Lista de items configurados
   * @return items
  **/
  @Schema(description = "Lista de items configurados")
  public List<Item> getItems() {
    return items;
  }

  public void setItems(List<Item> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationsLimits configurationsLimits = (ConfigurationsLimits) o;
    return Objects.equals(this.group, configurationsLimits.group) &&
        Objects.equals(this.items, configurationsLimits.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(group, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationsLimits {\n");
    
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
