/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import mx.wire4.model.WebHookDepositAuthorizationRequest;
/**
 * Contiene la información de la autorización de depósitos
 */
@Schema(description = "Contiene la información de la autorización de depósitos")


public class DepositAuthorizationRequest {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("webhook")
  private WebHookDepositAuthorizationRequest webhook = null;

  @SerializedName("wh_uuid")
  private String whUuid = null;

  public DepositAuthorizationRequest enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Indica sí se aplica la autorización de depósitos.
   * @return enabled
  **/
  @Schema(description = "Indica sí se aplica la autorización de depósitos.")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public DepositAuthorizationRequest webhook(WebHookDepositAuthorizationRequest webhook) {
    this.webhook = webhook;
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  @Schema(description = "")
  public WebHookDepositAuthorizationRequest getWebhook() {
    return webhook;
  }

  public void setWebhook(WebHookDepositAuthorizationRequest webhook) {
    this.webhook = webhook;
  }

  public DepositAuthorizationRequest whUuid(String whUuid) {
    this.whUuid = whUuid;
    return this;
  }

   /**
   * Identificador del webhook.
   * @return whUuid
  **/
  @Schema(description = "Identificador del webhook.")
  public String getWhUuid() {
    return whUuid;
  }

  public void setWhUuid(String whUuid) {
    this.whUuid = whUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositAuthorizationRequest depositAuthorizationRequest = (DepositAuthorizationRequest) o;
    return Objects.equals(this.enabled, depositAuthorizationRequest.enabled) &&
        Objects.equals(this.webhook, depositAuthorizationRequest.webhook) &&
        Objects.equals(this.whUuid, depositAuthorizationRequest.whUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, webhook, whUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositAuthorizationRequest {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("    whUuid: ").append(toIndentedString(whUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
