/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DepositantsResponse
 */


public class DepositantsResponse {
  @SerializedName("clabe")
  private String clabe = null;

  public DepositantsResponse clabe(String clabe) {
    this.clabe = clabe;
    return this;
  }

   /**
   * Cuenta clabe del depositante
   * @return clabe
  **/
  @Schema(description = "Cuenta clabe del depositante")
  public String getClabe() {
    return clabe;
  }

  public void setClabe(String clabe) {
    this.clabe = clabe;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositantsResponse depositantsResponse = (DepositantsResponse) o;
    return Objects.equals(this.clabe, depositantsResponse.clabe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clabe);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositantsResponse {\n");
    
    sb.append("    clabe: ").append(toIndentedString(clabe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
