/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import mx.wire4.model.Depositant;
/**
 * Objeto que contiene una lista de depositantes
 */
@Schema(description = "Objeto que contiene una lista de depositantes")

public class GetDepositants {
  @SerializedName("depositants")
  private List<Depositant> depositants = new ArrayList<>();

  public GetDepositants depositants(List<Depositant> depositants) {
    this.depositants = depositants;
    return this;
  }

  public GetDepositants addDepositantsItem(Depositant depositantsItem) {
    this.depositants.add(depositantsItem);
    return this;
  }

   /**
   * Lista de depositantes que contiene cada depositante encontrado
   * @return depositants
  **/
  @Schema(required = true, description = "Lista de depositantes que contiene cada depositante encontrado")
  public List<Depositant> getDepositants() {
    return depositants;
  }

  public void setDepositants(List<Depositant> depositants) {
    this.depositants = depositants;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDepositants getDepositants = (GetDepositants) o;
    return Objects.equals(this.depositants, getDepositants.depositants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(depositants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDepositants {\n");
    
    sb.append("    depositants: ").append(toIndentedString(depositants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
