/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import mx.wire4.model.Operations;
/**
 * PagerResponseDto
 */


public class PagerResponseDto {
  @SerializedName("content")
  private List<Operations> content = null;

  @SerializedName("number_of_elements")
  private Integer numberOfElements = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("size")
  private Integer size = null;

  @SerializedName("total_items")
  private Long totalItems = null;

  @SerializedName("total_pages")
  private Integer totalPages = null;

  public PagerResponseDto content(List<Operations> content) {
    this.content = content;
    return this;
  }

  public PagerResponseDto addContentItem(Operations contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Contenido de la respuesta paginada
   * @return content
  **/
  @Schema(description = "Contenido de la respuesta paginada")
  public List<Operations> getContent() {
    return content;
  }

  public void setContent(List<Operations> content) {
    this.content = content;
  }

  public PagerResponseDto numberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Numero de elementos en la pagina
   * @return numberOfElements
  **/
  @Schema(description = "Numero de elementos en la pagina")
  public Integer getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public PagerResponseDto page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Número de pagina
   * @return page
  **/
  @Schema(description = "Número de pagina")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public PagerResponseDto size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Tamaño de la pagina
   * @return size
  **/
  @Schema(description = "Tamaño de la pagina")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public PagerResponseDto totalItems(Long totalItems) {
    this.totalItems = totalItems;
    return this;
  }

   /**
   * Numero total de elementos de la consulta
   * @return totalItems
  **/
  @Schema(description = "Numero total de elementos de la consulta")
  public Long getTotalItems() {
    return totalItems;
  }

  public void setTotalItems(Long totalItems) {
    this.totalItems = totalItems;
  }

  public PagerResponseDto totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Numero total de paginas
   * @return totalPages
  **/
  @Schema(description = "Numero total de paginas")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagerResponseDto pagerResponseDto = (PagerResponseDto) o;
    return Objects.equals(this.content, pagerResponseDto.content) &&
        Objects.equals(this.numberOfElements, pagerResponseDto.numberOfElements) &&
        Objects.equals(this.page, pagerResponseDto.page) &&
        Objects.equals(this.size, pagerResponseDto.size) &&
        Objects.equals(this.totalItems, pagerResponseDto.totalItems) &&
        Objects.equals(this.totalPages, pagerResponseDto.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, numberOfElements, page, size, totalItems, totalPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagerResponseDto {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
