/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import mx.wire4.model.Payment;
/**
 * Contiene el conjunto de transacciones SPEI y SPID registradas bajo una misma petición
 */
@Schema(description = "Contiene el conjunto de transacciones SPEI y SPID registradas bajo una misma petición")


public class PaymentsSpeiAndSpidOrderId {
  @SerializedName("spei")
  private List<Payment> spei = null;

  @SerializedName("spid")
  private List<Payment> spid = null;

  public PaymentsSpeiAndSpidOrderId spei(List<Payment> spei) {
    this.spei = spei;
    return this;
  }

  public PaymentsSpeiAndSpidOrderId addSpeiItem(Payment speiItem) {
    if (this.spei == null) {
      this.spei = new ArrayList<>();
    }
    this.spei.add(speiItem);
    return this;
  }

   /**
   * Lista de las transacciones spei registradas
   * @return spei
  **/
  @Schema(description = "Lista de las transacciones spei registradas")
  public List<Payment> getSpei() {
    return spei;
  }

  public void setSpei(List<Payment> spei) {
    this.spei = spei;
  }

  public PaymentsSpeiAndSpidOrderId spid(List<Payment> spid) {
    this.spid = spid;
    return this;
  }

  public PaymentsSpeiAndSpidOrderId addSpidItem(Payment spidItem) {
    if (this.spid == null) {
      this.spid = new ArrayList<>();
    }
    this.spid.add(spidItem);
    return this;
  }

   /**
   * Lista de las transacciones spid registradas
   * @return spid
  **/
  @Schema(description = "Lista de las transacciones spid registradas")
  public List<Payment> getSpid() {
    return spid;
  }

  public void setSpid(List<Payment> spid) {
    this.spid = spid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentsSpeiAndSpidOrderId paymentsSpeiAndSpidOrderId = (PaymentsSpeiAndSpidOrderId) o;
    return Objects.equals(this.spei, paymentsSpeiAndSpidOrderId.spei) &&
        Objects.equals(this.spid, paymentsSpeiAndSpidOrderId.spid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spei, spid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentsSpeiAndSpidOrderId {\n");
    
    sb.append("    spei: ").append(toIndentedString(spei)).append("\n");
    sb.append("    spid: ").append(toIndentedString(spid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
