/*
 * Wire4RestAPI
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PaymentRequestResponse
 */



public class PaymentRequestResponse {
  @SerializedName("reference")
  private String reference = null;

  @SerializedName("request_id")
  private String requestId = null;

  @SerializedName("url")
  private String url = null;

  public PaymentRequestResponse reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Es la referencia de pago generada para la petición (solicitud).
   * @return reference
  **/
  @Schema(description = "Es la referencia de pago generada para la petición (solicitud).")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public PaymentRequestResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Es el identificador público generado para la petición (solicitud).
   * @return requestId
  **/
  @Schema(description = "Es el identificador público generado para la petición (solicitud).")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public PaymentRequestResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url del portal en donde se debe capturar los datos de la tarjeta para aplicar el cargo
   * @return url
  **/
  @Schema(description = "Url del portal en donde se debe capturar los datos de la tarjeta para aplicar el cargo")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequestResponse paymentRequestResponse = (PaymentRequestResponse) o;
    return Objects.equals(this.reference, paymentRequestResponse.reference) &&
        Objects.equals(this.requestId, paymentRequestResponse.requestId) &&
        Objects.equals(this.url, paymentRequestResponse.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, requestId, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequestResponse {\n");
    
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
