/*
 * Wire4RestAPI
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package mx.wire4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import mx.wire4.model.ConfigurationsLimits;
/**
 * Contiene el listado de grupo de configuraciones para actualizar
 */
@Schema(description = "Contiene el listado de grupo de configuraciones para actualizar")

public class UpdateConfigurationsRequestDTO {
  @SerializedName("configurations")
  private List<ConfigurationsLimits> configurations = new ArrayList<>();

  public UpdateConfigurationsRequestDTO configurations(List<ConfigurationsLimits> configurations) {
    this.configurations = configurations;
    return this;
  }

  public UpdateConfigurationsRequestDTO addConfigurationsItem(ConfigurationsLimits configurationsItem) {
    this.configurations.add(configurationsItem);
    return this;
  }

   /**
   * Listado de configuraciones para actualizar
   * @return configurations
  **/
  @Schema(required = true, description = "Listado de configuraciones para actualizar")
  public List<ConfigurationsLimits> getConfigurations() {
    return configurations;
  }

  public void setConfigurations(List<ConfigurationsLimits> configurations) {
    this.configurations = configurations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateConfigurationsRequestDTO updateConfigurationsRequestDTO = (UpdateConfigurationsRequestDTO) o;
    return Objects.equals(this.configurations, updateConfigurationsRequestDTO.configurations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configurations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateConfigurationsRequestDTO {\n");
    
    sb.append("    configurations: ").append(toIndentedString(configurations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
